#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Test-File-ShareDir-Dist
Version  : 1.001002
Release  : 14
URL      : https://cpan.metacpan.org/authors/id/K/KE/KENTNL/Test-File-ShareDir-1.001002.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/K/KE/KENTNL/Test-File-ShareDir-1.001002.tar.gz
Summary  : 'Create a Fake ShareDir for your modules for testing.'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
BuildRequires : buildreq-cpan
BuildRequires : perl(Class::Inspector)
BuildRequires : perl(Class::Tiny)
BuildRequires : perl(File::Copy::Recursive)
BuildRequires : perl(File::ShareDir)
BuildRequires : perl(Path::Tiny)
BuildRequires : perl(Scope::Guard)
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Try::Tiny)

%description
Test::File::ShareDir
"Test::File::ShareDir" is some low level plumbing to enable a
distribution to perform tests while consuming its own "share"
directories in a manner similar to how they will be once installed.

%prep
%setup -q -n Test-File-ShareDir-1.001002

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Test-File-ShareDir-Dist
cp LICENSE %{buildroot}/usr/share/package-licenses/perl-Test-File-ShareDir-Dist/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
