#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Test-File-ShareDir-Dist
Version  : 1.001001
Release  : 2
URL      : http://search.cpan.org/CPAN/authors/id/K/KE/KENTNL/Test-File-ShareDir-1.001001.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/K/KE/KENTNL/Test-File-ShareDir-1.001001.tar.gz
Summary  : 'Create a Fake ShareDir for your modules for testing.'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Test-File-ShareDir-Dist-doc
BuildRequires : perl(Class::Inspector)
BuildRequires : perl(Class::Tiny)
BuildRequires : perl(File::Copy::Recursive)
BuildRequires : perl(File::ShareDir)
BuildRequires : perl(Path::Tiny)
BuildRequires : perl(Scope::Guard)
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Try::Tiny)

%description
Test::File::ShareDir
"Test::File::ShareDir" is some low level plumbing to enable a
distribution to perform tests while consuming its own "share"
directories in a manner similar to how they will be once installed.

%package doc
Summary: doc components for the perl-Test-File-ShareDir-Dist package.
Group: Documentation

%description doc
doc components for the perl-Test-File-ShareDir-Dist package.


%prep
%setup -q -n Test-File-ShareDir-1.001001

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Test/File/ShareDir.pm
/usr/lib/perl5/site_perl/5.26.1/Test/File/ShareDir/Dist.pm
/usr/lib/perl5/site_perl/5.26.1/Test/File/ShareDir/Module.pm
/usr/lib/perl5/site_perl/5.26.1/Test/File/ShareDir/Object/Dist.pm
/usr/lib/perl5/site_perl/5.26.1/Test/File/ShareDir/Object/Inc.pm
/usr/lib/perl5/site_perl/5.26.1/Test/File/ShareDir/Object/Module.pm
/usr/lib/perl5/site_perl/5.26.1/Test/File/ShareDir/TempDirObject.pm
/usr/lib/perl5/site_perl/5.26.1/Test/File/ShareDir/Utils.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
